name: pacman
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_joystick: ^0.2.1
  flutter_lints: ^4.0.0
  font_awesome_flutter: ^10.7.0

flutter:
  uses-material-design: true

  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf

  assets:
    - assets/fonts/PressStart2P-Regular.ttf
